### ISSUE TITLE
Create User parser with UserDTO and NewUser

### ISSUE THREAD

**Issue by gerigol** [CodecoolArchive2023/el-proyecte-grande-sprint-1-java-tuszmak#5]
Create a Mapper class that converts User
- [x] create method that converts User to UserDTO (UserDTO doesn't have a password)
- [x] create method that converts NewUser to User

**Comment by gerigol** [comment]
I have two solutions in mind for parsing User:
* create static method called "of" in UserDTO that creates a new UserDTO from a User and similarly the NewUser has a method to create a new User from the newUser object
* create a Mapper class that has two static methods mapToUserDTO and mapToUser (I picked this solution)

**Comment by tuszmak** [comment]
Reviewed by Benec, it's fine!
